config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

 	get '/', to: 'auction#index'

 	# Tạo ra categories và category/:id/product_type
 	resources :category do
 		collection do
 			post 'get_product_type'
 		end

 		resources :product_type
 	end

 	# Tạo ra /customer và /customer/:id/product và /customer/:id/auction, ....
 	resources :customer do
 		resources :product
 		resources :auction
 		resources :favorite_list
 		resources :receipt do
 			get 'pay'	
 			post 'hook'
 		end

 		resources :invoice
 		resources :report
 		resources :review
 		resources :complaint
 		resources :notification
 	end

 	# Tạo ra /employee/:id/complaint
 	resources :employee do
 		resources :complaint
 	end

 	# Tạo ra /auction
 	resources :auction do
 		collection do
 			post 'bid'
 		end

 		post 'buy_it_now'

 		resources :auction_detail
 	end
  
 	resources :product_examination
end

app/models/auction.rb
class Auction < ApplicationRecord
  	belongs_to :product

  	class << self
	  	def KetThucPhien(auction_id)
	  		p "Ket thuc phien"

			current_price = Auction.select("current_price")
				.where("auction_id = " + auction_id)[0].current_price

			winner = CustomersOfAuction.joins(:auction_details).select("customer_id")
				.where("auction_details.bid_amount = " + current_price + 
				" and auction_id = " + auction_id)[0].customer_id

			Notification.create!(id: Notification.maximum("id") + 1, title: "Chiến thắng đấu giá " + auction_id,
			 content: "Thắng đấu giá", sending_time: Time.now, customer_id: winner)

			Receipt.create!(id: Receipt.maximum("id") + 1, auction_id: auction_id, customer_id: winner,
			 card_number: nil, product_received: 0, status: 0, total_amount: current_price)

			Invoice.create!(id: Invoice.maximum("id") + 1, receipt_id: Receipt.maximum("id"), 
				card_number: nil, total_amount: current_price * 5 / 100)
		end
	end
end

app/models/auction_detail.rb
class AuctionDetail < ApplicationRecord
  belongs_to :customers_of_auction
end

app/models/category.rb
class Category < ApplicationRecord
	has_many :product_types, :foreign_key => 'category_id'
end

app/models/complaint.rb
class Complaint < ApplicationRecord
  belongs_to :customer
  belongs_to :employee
end

app/models/customer.rb
class Customer < ApplicationRecord
	has_many :products
	has_many :complaints
	has_many :notifications
	has_many :reports
	has_many :reviews
end

app/models/employee.rb
class Employee < ApplicationRecord
	has_many :complaints
	has_many :reports
end

app/models/favorite_list.rb
class FavoriteList < ApplicationRecord
  self.primary_keys = :customer_id, :auction_id
  belongs_to :customer
  belongs_to :auction
end

app/models/image.rb
class Image < ApplicationRecord
  	belongs_to :product

  	has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/app/public/MissingImage.jpg"
  	validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

app/models/invoice.rb
class Invoice < ApplicationRecord
  belongs_to :receipt
end

app/models/notification.rb
class Notification < ApplicationRecord
  belongs_to :customer
end

app/models/product.rb
class Product < ApplicationRecord
  	belongs_to :product_type
 	belongs_to :customer
 	has_many :auctions
 	has_many :images
end

app/models/product_examination.rb
class ProductExamination < ApplicationRecord
  belongs_to :product
  belongs_to :employee, optional: true
end

app/models/product_type.rb
class ProductType < ApplicationRecord
  	belongs_to :category
  	has_many :products
end

app/models/receipt.rb
class Receipt < ApplicationRecord
  belongs_to :auction
  belongs_to :customer
  has_many :reports

  def paypal_url(return_path, notify_url)
  	p "Notify_url: #{Rails.application.secrets.app_host}#{notify_url}"
  	values = {
			business: "thienphuvuong-facilitator@gmail.com",
			cmd: "_xclick",
			upload: 1,
			return: "#{Rails.application.secrets.app_host}#{return_path}",
	        invoice: id,
	        amount: total_amount,
	        item_name: Product.joins(:auctions).select("product_name").where("auctions.id = " + auction_id.to_s)[0].product_name,
	        item_number: auction_id,
	        quantity: '1',
	        notify_url: "#{Rails.application.secrets.app_host}#{notify_url}"
		}

	"#{Rails.application.secrets.paypal_host}/cgi-bin/webscr?" + values.to_query
  end
end

app/models/report.rb
class Report < ApplicationRecord
  belongs_to :receipt
  belongs_to :customer, optional: true
  belongs_to :employee, optional: true
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :customer, optional: true
  belongs_to :receipt
end

app/controllers/product_examination_controller.rb
class ProductExaminationController < ApplicationController
	def index
		# @productexaminations = ProductExamination.where(status: 0)

		@mas = Image.joins("INNER JOIN products ON products.id = images.product_id INNER JOIN product_examinations ON products.id = product_examinations.product_id and status = 0")
		.where("images.id in (select id from images where product_id = products.id order by id DESC limit 1)")
		.select("product_examinations.*, products.description, products.product_name, images.*, product_examinations.id as foo")

		render layout: "without_sidebar_carousel"
	end

	def show
		
	end

	def edit
		@productexamination = ProductExamination.find(params[:id])

		@mas = Image.joins("INNER JOIN products ON products.id = images.product_id INNER JOIN product_examinations ON products.id = product_examinations.product_id and product_examinations.id = "+params[:id])
		.where("images.id in (select id from images where product_id = products.id order by id DESC)")
		.select("product_examinations.*, products.description, products.product_name, images.*, product_examinations.id as foo")

		render layout: "without_sidebar_carousel"
	end

	def update
		@productexamination = ProductExamination.find(params[:id])
		
		# @productexamination.employee = NHANVIENXETDUYET !!!!!!!!!!!!!!!!!!!!! #######################################
		# @productexamination.update(params.require(:productexamination).permit(:employee, :reason, :status))
		
		@productexamination.update(params.require(:product_examination).permit(:reason, :status))
		@productexamination.update_attribute(:examination_time, DateTime.now)			

		# GUIMAILCHOKHACHHANG !!!!!!!!!!!!!!!!!!!!!!
		# 
		# 
		# 
		# 
		# 
		
		# GUITHONGBAOCHOKHACHHANG !!!!!!!!!!!!!!!!!
		noti = @productexamination.product.customer.notifications.new
		noti.id = Notification.maximum("id") + 1
		noti.content = "Lý do: " + @productexamination.reason
		noti.sending_time = DateTime.now
		if (@productexamination.status == 1)
			noti.title = "Sản phẩm " + @productexamination.product.product_name + "của bạn không được duyệt"
		end

		if (@productexamination.status == 2)
			noti.title = "Sản phẩm " + @productexamination.product.product_name + "của bạn đã được duyệt"
		end

		noti.save
		
		redirect_to product_examination_index_path
	end
end

app/helpers/auction_helper.rb
module AuctionHelper
end

app/helpers/image_helper.rb
module ImageHelper
end

app/helpers/invoice_helper.rb
module InvoiceHelper
end

app/helpers/product_examination_helper.rb
module ProductExaminationHelper
end

app/helpers/report_helper.rb
module ReportHelper
end

app/helpers/review_helper.rb
module ReviewHelper
end

app/views/product_examination/_form.html.erb
<%= form_with(model: product_examination, local: true) do |f| %>
<div class="form-group">
	<label>Title</label>
	<%= f.text_field :title, class: 'form-control' %>
</div>
<div class="form-group">
	<label>Body</label>
	<%= f.text_area :body, class: 'form-control' %>
</div>
<button type="submit" class="btn btn-primary"><%= fa_icon "save" %> Save </button>
<% end %>

app/views/product_examination/edit.html.erb
<% @temp = 0 %>
<div id="mainBody">
 <div class="container">
  <!-- <div class="row">	   -->
   <div id="gallery" class="span3 col-md-4">
    <% @mas.each do |ma| %>
      <% if @temp == 0 %>
        <img src="<%= image_path ma.image.url %>" style="width:270px" alt=""/>
        <% @temp = 1 %>
        <div id="differentview" class="moreOptopm carousel slide">
        <div class="carousel-inner">
      <br>
      <% else %>
      
        <!-- <div class="item active"> -->
         <a href=""> <img style="width:85px" src="<%= image_path ma.image.url %>" alt=""/></a>
        <!-- </div> -->
                 <!-- <div class="item">
                   <a href="themes/images/products/large/f3.jpg" > <img style="width:29%" src="themes/images/products/large/f3.jpg" alt=""/></a>
                   <a href="themes/images/products/large/f1.jpg"> <img style="width:29%" src="themes/images/products/large/f1.jpg" alt=""/></a>
                   <a href="themes/images/products/large/f2.jpg"> <img style="width:29%" src="themes/images/products/large/f2.jpg" alt=""/></a>
                 </div> -->
        
                <!--  
  			  <a class="left carousel-control" href="#myCarousel" data-slide="prev">‹</a>
                <a class="right carousel-control" href="#myCarousel" data-slide="next">›</a> 
              -->
              <% end %>
                  <% end %>
      </div>
      </div>
     

        </div>

        <div class="span8 col-md-8">
          <!-- 	<br class="clr"> -->
          <h3><%= @productexamination.product.product_name %></h3>
          <div><%= @productexamination.product.customer.customer_name %></div>
          <div>Danh mục: <%= @productexamination.product.product_type.category.category_name %></div>
          <div>Loại SP: <%= @productexamination.product.product_type.product_type_name %></div>

          <hr class="soft"/>

          <%= form_with scope: :product_examination, url: product_examination_path, method: :put, local: true do |f|%>
          <div class="form-group">
            <!-- <label>Title</label> -->
            <label class="btn btn-success">
              <%= f.radio_button :status, '2', :checked => true %> Duyệt
            </label>
            <label class="btn btn-danger">
              <%= f.radio_button :status, '1' %> Không Duyệt
            </label>
          </div>

          <div class="form-group">
            <br>
            <!-- <label>Lý do</label> -->
            <%= f.text_area :reason, placeholder: "Lý do", class: 'form-control', rows: "4" %>
          </div>

          <br>
          <button type="submit" class="btn">Gửi kết quả</button>
          <% end %>
          
          <br>

        
        <br>
        <div class="span12">

         <div id="myTabContent" class="tab-content">
          <div class="tab-pane fade active in" id="home">

           <h4>Product Information</h4>

           <p>
            <%= @productexamination.product.description %> 
          </p>
        </div>

      </div>
    </div>
</div>
    <!-- </div> -->
  </div>
</div>

app/views/product_examination/index.html.erb
<h3 class="container">Duyệt Sản phẩm</h3>
<br>
<div class="container-fluid">
	<% @mas.each do |ma| %>

	<div class="col-lg-3">
		<div class="thumbnail">
			<!-- <i class="tag"></i> -->

			<a href="<%= edit_product_examination_path(ma.foo) %>"><img src="<%= image_path ma.image.url %>" alt=""/></a>

			<div class="caption">

				<h5><%= ma.product.product_name %></h5>
				<p><%= ma.product.description.truncate(100) %></p>
				<h4 style="text-align:center"><a class="btn btn-success" href="<%= edit_product_examination_path(ma.foo) %>">Kiểm tra</a> </h4>		  
			</div>

		</div>	
	</div>
	<% end %>

</div>

app/views/product_examination/show.html.erb
		<div id="mainBody">
			<div class="container">
				<!-- <div class="row">	   -->
					<div id="gallery" class="span3">
						<!-- <a href="themes/images/products/large/f1.jpg" title=""> -->
							<img src="themes/images/products/large/3.jpg" style="width:100%" alt=""/>
						<!-- </a> -->
						<div id="differentview" class="moreOptopm carousel slide">
							<div class="carousel-inner">
								<div class="item active">
									<a href="themes/images/products/large/f1.jpg"> <img style="width:29%" src="themes/images/products/large/f1.jpg" alt=""/></a>
									<a href="themes/images/products/large/f2.jpg"> <img style="width:29%" src="themes/images/products/large/f2.jpg" alt=""/></a>
									<a href="themes/images/products/large/f3.jpg" > <img style="width:29%" src="themes/images/products/large/f3.jpg" alt=""/></a>
								</div>
								<div class="item">
									<a href="themes/images/products/large/f3.jpg" > <img style="width:29%" src="themes/images/products/large/f3.jpg" alt=""/></a>
									<a href="themes/images/products/large/f1.jpg"> <img style="width:29%" src="themes/images/products/large/f1.jpg" alt=""/></a>
									<a href="themes/images/products/large/f2.jpg"> <img style="width:29%" src="themes/images/products/large/f2.jpg" alt=""/></a>
								</div>
							</div>
              <!--  
			  <a class="left carousel-control" href="#myCarousel" data-slide="prev">‹</a>
              <a class="right carousel-control" href="#myCarousel" data-slide="next">›</a> 
          -->
      </div>

  </div>
  <div class="span8">
  <!-- 	<br class="clr"> -->
  	<h3><%= @productexamination.product.product_name %></h3>
  	<div><%= @productexamination.product.customer.customer_name %></div>
  	<div>Danh mục: <%= @productexamination.product.product_type.category.category_name %></div>
  	<div>Loại SP: <%= @productexamination.product.product_type.product_type_name %></div>

  	<hr class="soft"/>

  	<label class="btn btn-success">
  		<input type="radio" name="options" id="option1" autocomplete="off" checked>Duyệt
  	</label>
  	<label class="btn btn-danger">
  		<input type="radio" name="options" id="option2" autocomplete="off">Không duyệt
  	</label>

  	<div>
  		<br>
  		<textarea rows="5" style="width: 98%" id="textarea" class="" placeholder="Lý do"></textarea>
	  	<button type="submit" class="btn">Gửi kết quả</button>
  	</div>

<!--   	<button type="submit" class="btn btn-success">Duyệt</button>
  	<button type="submit" class="btn btn-danger">Không duyệt</button>
  -->  </div>
<br>
  <div class="span12">

  	<div id="myTabContent" class="tab-content">
  		<div class="tab-pane fade active in" id="home">
  			<h4>Product Information</h4>
  			
  			<p>
  				<%= @productexamination.product.description %> 
  			</p>
  		</div>
  		
  	</div>
  </div>

  <!-- </div> -->
</div>
</div>