config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

 	get '/', to: 'auction#index'

 	# Tạo ra categories và category/:id/product_type
 	resources :category do
 		collection do
 			post 'get_product_type'
 		end

 		resources :product_type
 	end

 	# Tạo ra /customer và /customer/:id/product và /customer/:id/auction, ....
 	resources :customer do
 		resources :product
 		resources :auction
 		resources :favorite_list
 		resources :receipt do
 			get 'pay'	
 			post 'hook'
 		end

 		resources :invoice
 		resources :report
 		resources :review
 		resources :complaint
 		resources :notification
 	end

 	# Tạo ra /employee/:id/complaint
 	resources :employee do
 		resources :complaint
 	end

 	# Tạo ra /auction
 	resources :auction do
 		collection do
 			post 'bid'
 		end

 		post 'buy_it_now'

 		resources :auction_detail
 	end
  
 	resources :product_examination
end

app/models/auction.rb
class Auction < ApplicationRecord
  	belongs_to :product

  	class << self
	  	def KetThucPhien(auction_id)
	  		p "Ket thuc phien"

			current_price = Auction.select("current_price")
				.where("auction_id = " + auction_id)[0].current_price

			winner = CustomersOfAuction.joins(:auction_details).select("customer_id")
				.where("auction_details.bid_amount = " + current_price + 
				" and auction_id = " + auction_id)[0].customer_id

			Notification.create!(id: Notification.maximum("id") + 1, title: "Chiến thắng đấu giá " + auction_id,
			 content: "Thắng đấu giá", sending_time: Time.now, customer_id: winner)

			Receipt.create!(id: Receipt.maximum("id") + 1, auction_id: auction_id, customer_id: winner,
			 card_number: nil, product_received: 0, status: 0, total_amount: current_price)

			Invoice.create!(id: Invoice.maximum("id") + 1, receipt_id: Receipt.maximum("id"), 
				card_number: nil, total_amount: current_price * 5 / 100)
		end
	end
end

app/models/auction_detail.rb
class AuctionDetail < ApplicationRecord
  belongs_to :customers_of_auction
end

app/models/category.rb
class Category < ApplicationRecord
	has_many :product_types, :foreign_key => 'category_id'
end

app/models/complaint.rb
class Complaint < ApplicationRecord
  belongs_to :customer
  belongs_to :employee
end

app/models/customer.rb
class Customer < ApplicationRecord
	has_many :products
	has_many :complaints
	has_many :notifications
	has_many :reports
	has_many :reviews
end

app/models/employee.rb
class Employee < ApplicationRecord
	has_many :complaints
	has_many :reports
end

app/models/favorite_list.rb
class FavoriteList < ApplicationRecord
  self.primary_keys = :customer_id, :auction_id
  belongs_to :customer
  belongs_to :auction
end

app/models/image.rb
class Image < ApplicationRecord
  	belongs_to :product

  	has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/app/public/MissingImage.jpg"
  	validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

app/models/invoice.rb
class Invoice < ApplicationRecord
  belongs_to :receipt
end

app/models/notification.rb
class Notification < ApplicationRecord
  belongs_to :customer
end

app/models/product.rb
class Product < ApplicationRecord
  	belongs_to :product_type
 	belongs_to :customer
 	has_many :auctions
 	has_many :images
end

app/models/product_type.rb
class ProductType < ApplicationRecord
  	belongs_to :category
  	has_many :products
end

app/models/receipt.rb
class Receipt < ApplicationRecord
  belongs_to :auction
  belongs_to :customer
  has_many :reports

  def paypal_url(return_path, notify_url)
  	p "Notify_url: #{Rails.application.secrets.app_host}#{notify_url}"
  	values = {
			business: "thienphuvuong-facilitator@gmail.com",
			cmd: "_xclick",
			upload: 1,
			return: "#{Rails.application.secrets.app_host}#{return_path}",
	        invoice: id,
	        amount: total_amount,
	        item_name: Product.joins(:auctions).select("product_name").where("auctions.id = " + auction_id.to_s)[0].product_name,
	        item_number: auction_id,
	        quantity: '1',
	        notify_url: "#{Rails.application.secrets.app_host}#{notify_url}"
		}

	"#{Rails.application.secrets.paypal_host}/cgi-bin/webscr?" + values.to_query
  end
end

app/models/report.rb
class Report < ApplicationRecord
  belongs_to :receipt
  belongs_to :customer, optional: true
  belongs_to :employee, optional: true
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :customer, optional: true
  belongs_to :receipt
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  	protect_from_forgery with: :exception
end

app/helpers/application_helper.rb
module ApplicationHelper
	def categories_navbar
	 	categories = Category.select("category_name")
	 	select_input = ""

	 	categories.each do |category|
            select_input += "<option>#{category.category_name}</option>"
        end

        return select_input.html_safe
	end

	def sidebar
	 	product_types = ProductType.joins(:category).select("categories.id as cate_id, product_types.id as prod_id, categories.category_name, product_types.product_type_name").order("category_name DESC").distinct
	 	sidebar = ""
	 	category_name = product_types[0].category_name
	 	sidebar = "<li class=\"subMenu open\"><a> #{category_name}</a><ul style=\"display:none\">"

	 	product_types.each do |product_type|
	 		if product_type.category_name != category_name
	 			category_name = product_type.category_name
	 			sidebar += "</ul></li><li class=\"subMenu open\"><a> #{product_type.category_name}</a><ul style=\"display:none\">"
	 			sidebar += "<li><a href=\"" + category_product_type_path(product_type.cate_id, product_type.prod_id) + "\"><i class=\"fa fa-chevron-right\"></i> #{product_type.product_type_name}</a></li>"
	 		else
	 			sidebar += "<li><a href=\"" + category_product_type_path(product_type.cate_id, product_type.prod_id) + "\"><i class=\"fa fa-chevron-right\"></i> #{product_type.product_type_name}</a></li>"
	 		end     
        end

        sidebar += "</ul></li>"

        return sidebar.html_safe
	end

	def hot_auctions_sidebar
		auctions = Image.joins("INNER JOIN products ON products.id = images.product_id INNER JOIN auctions ON products.id = auctions.product_id")
		.where("images.id in (select id from images where product_id = products.id order by id DESC limit 1) and to_timestamp(ending_time,'yyyy-mm-dd HH24:MI:ss') > NOW()")
		.select("auctions.id as auction_id, auctions.current_price, products.description, products.product_name, auctions.created_at, images.*").limit(2)

		hot_auctions = ""

		auctions.each do |auction|
			hot_auctions += "<div class=\"thumbnail\"><img src=\"" + image_path(auction.image.url) +
			 "\" title=\"Bootshop New Kindel\" alt=\"Bootshop Kindel\"><div class=\"caption\">" + 
			 "<h5>#{auction.product_name}</h5><h4 style=\"text-align:center\"><a class=\"btn btn-success\">" + 
			 " #{auction.current_price} VNĐ </a> <a class=\"btn btn-default\" href=\"#\">Thêm vào <i class=\"fa fa-eye\"" + 
			 " aria-hidden=\"true\"></i></a> <a class=\"btn btn-primary\" href=\"" + auction_path(auction.auction_id) + "\"><i class=\"fa fa-gavel\" aria-hidden=\"true\"></i></a></h4></div></div><br/>"     
		end  
    
		return hot_auctions.html_safe
    end
end

app/helpers/auction_helper.rb
module AuctionHelper
end

app/helpers/image_helper.rb
module ImageHelper
end

app/helpers/invoice_helper.rb
module InvoiceHelper
end

app/helpers/report_helper.rb
module ReportHelper
end

app/helpers/review_helper.rb
module ReviewHelper
end

app/views/application/_bootstrap_jquery.html.erb
<!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">

<!-- jQuery library -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>

<!-- Latest compiled JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script> 

<!-- font-awesome -->
<script src="https://use.fontawesome.com/ad779edd18.js"></script>

app/views/application/_carousel.html.erb
<div id="myCarousel" class="carousel slide" data-ride="carousel">
  <!-- Indicators -->
  <ol class="carousel-indicators">
    <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
    <li data-target="#myCarousel" data-slide-to="1"></li>
    <li data-target="#myCarousel" data-slide-to="2"></li>
  </ol>

  <!-- Wrapper for slides -->
  <div class="carousel-inner">
    <div class="item active">
      <img src="<%= image_path "images/carousel/1.png" %>" alt="Los Angeles">
    </div>

    <div class="item">
      <img src="<%= image_path "images/carousel/2.png" %>" alt="Chicago">
    </div>

    <div class="item">
      <img src="<%= image_path "images/carousel/3.png" %>" alt="New York">
    </div>
  </div>

  <!-- Left and right controls -->
  <a class="left carousel-control" href="#myCarousel" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="right carousel-control" href="#myCarousel" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right"></span>
    <span class="sr-only">Next</span>
  </a>
</div>

app/views/application/_footer.html.erb
<!-- Footer ================================================================== -->
<footer id="footerSection" >
    <div class="container">
        <div class="row">
            <div class="col-lg-3">
                <h5>ACCOUNT</h5>
                <ul class="list-group">
                    <li class="footer-list"><a href="login.html">YOUR ACCOUNT</a></li>
                    <li class="footer-list"><a href="login.html">PERSONAL INFORMATION</a></li>
                    <li class="footer-list"><a href="login.html">ADDRESSES</a></li>
                    <li class="footer-list"><a href="login.html">DISCOUNT</a></li>
                    <li class="footer-list"><a href="login.html">ORDER HISTORY</a></li>
                </ul>
            </div>
            <div class="col-lg-3">
                <h5>INFORMATION</h5>
                <ul class="list-group">
                    <li class="footer-list"><a href="contact.html">CONTACT</a></li>
                    <li class="footer-list"><a href="register.html">REGISTRATION</a></li>
                    <li class="footer-list"><a href="legal_notice.html">LEGAL NOTICE</a></li>
                    <li class="footer-list"><a href="tac.html">TERMS AND CONDITIONS</a></li>
                    <li class="footer-list"><a href="faq.html">FAQ</a>
                </ul>
            </div>
            <div class="col-lg-3">
                <h5>OUR OFFERS</h5>
                <ul class="list-group">
                    <li class="footer-list"><a href="#">NEW PRODUCTS</a></li>
                    <li class="footer-list"><a href="#">TOP SELLERS</a></li>
                    <li class="footer-list"><a href="special_offer.html">SPECIAL OFFERS</a></li>
                    <li class="footer-list"><a href="#">MANUFACTURERS</a></li>
                    <li class="footer-list"><a href="#">SUPPLIERS</a></li>
                </ul>
            </div>
            <div id="socialMedia" class="col-lg-3">
                <h5>SOCIAL MEDIA </h5>
                <a href="#"><img width="60" height="60" src="<%= image_path "images/facebook.png" %>" title="facebook" alt="facebook"/></a>
                <a href="#"><img width="60" height="60" src="<%= image_path "images/twitter.png" %>" title="twitter" alt="twitter"/></a>
                <a href="#"><img width="60" height="60" src="<%= image_path "images/youtube.png" %>" title="youtube" alt="youtube"/></a>
            </div>
        </div>
        <p class="pull-right">&copy; Bootshop</p>
    </div>
    <!-- Container End -->
</footer>

app/views/application/_navbar.html.erb
<div id="header">
        <div class="container">
            <div id="welcomeLine" class="row  margin-top">
                <div class="col-lg-12">Xin chào!<strong> Nguyễn Văn A</strong>
                    <div class="pull-right">
                        <a href="<%= new_customer_product_path(1) %>"><span class="btn btn-xs btn-primary">Đăng sản phẩm</span> </a>
                        <a href="product_summary.html"><span class="btn btn-xs btn-primary"><i class="fa fa-eye"></i> [ 3 ] Phiên đấu giá bạn thích </span> </a>
                    </div>
                </div>
            </div>
            <!-- Navbar ================================================== <--></-->
            <div id="logoArea" class="navbar  navbar-inverse margin-top padding">
                <div class="container-fluid">
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#topMenu" aria-expanded="false">
                            <span class="sr-only">Toggle navigation</span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                        <a class="brand" href="index.html"><img src="<%= image_path "images/OdunAuction.png" %>" alt="Bootsshop"/></a>
                    </div>
                    <form method="post" action="products.html" class="navbar-form navbar-left">
                            <div class="form-group">
                                <div class="input-group">   
                                    <span class="input-group-addon"><i class="glyphicon glyphicon-search"></i></span>
                                    <input id="search" type="text" class="form-control input-sm" name="search" placeholder="Tìm kiếm">
                                </div>
                            </div>
                            <div class="form-group">
                                <select class="form-control input-sm">
                                    <option>Tất cả</option>
                                    <%= categories_navbar() %>
                                </select>
                            </div>
                            <button type="submit" id="submitButton" class="btn btn-primary">Tìm</button> 
                    </form>
                    <div class="collapse navbar-collapse" id="topMenu">
                        <ul class="nav navbar-nav navbar-right">
                            <li class="navbar-color"><a class="navbar-a" href="special_offer.html">Giảm giá</a></li>
                            <li class=""><a class="navbar-a" href="normal.html">Giao hàng</a></li>
                            <li class=""><a class="navbar-a" href="contact.html">Liên hệ</a></li>
                            <button class="btn btn-success navbar-btn btn-md" data-toggle="modal" data-target="#login">Đăng nhập</button>
                        </ul>
                        <div id="login" class="modal fade" role="dialog" tabindex="-1" role="dialog" aria-labelledby="login" aria-hidden="false" >
                            <div class="modal-dialog">
                                <!-- Modal content-->
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                                        <h4 class="modal-title">Đăng nhập</h4>
                                    </div>
                                    <div class="modal-body">
                                        <form  method="post" action="products.html">
                                            <div class="form-group">
                                                <label for="email">Email đăng nhập:</label>
                                                <input type="email" class="form-control" id="email">
                                            </div>
                                            <div class="form-group">
                                                <label for="pwd">Mật khẩu:</label>
                                                <input type="password" class="form-control" id="pwd">
                                            </div>
                                            <div class="checkbox">
                                                <label><input type="checkbox"> Nhớ tên đăng nhập và mật khẩu</label>
                                            </div>
                                            <button type="submit" class="btn btn-success">Đăng nhập</button>
                                            <a href="#" class="btn btn-warning" role="button">Đăng ký</a>
                                        </form> 

                                    </div>
                                    <div class="modal-footer">
                                        <button type="button" class="btn btn-info" data-dismiss="modal">Đóng</button>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
</div>
    <!-- Header End====================================================================== -->

app/views/application/_sidebar.html.erb
<!-- Sidebar ================================================== -->
<div id="sidebar" class="span3">
    <div class="well well-small"><a id="myCart" href="product_summary.html"><i class="fa fa-eye" aria-hidden="true"></i> Phiên đấu giá yêu thích</a></div>
    <ul id="sideManu" class="nav nav-tabs nav-stacked">
        <%= sidebar() %>
    </ul>
    <br/>
    <%= hot_auctions_sidebar() %>
    <div class="thumbnail">
        <img src="<%= image_path "images/payment_methods.png" %>" title="Bootshop Payment Methods" alt="Payments Methods">
        <div class="caption">
            <h5>Phương thức thanh toán</h5>
        </div>
    </div>
</div>
<!-- Sidebar end=============================================== -->

app/views/application/_themes_switcher.html.erb
<!-- Themes switcher section ============================================================================================= -->
<div id="secectionBox">
    <div id="themeContainer">
        <div id="hideme" class="themeTitle">Style Selector</div>
        <div class="themeName">Oregional Skin</div>
        <div class="images style">
            <a href="themes/css/#" name="bootshop"><img src="<%= image_path "switch/images/clr/bootshop.png" %>" alt="bootstrap business templates" class="active"></a>
            <a href="themes/css/#" name="businessltd"><img src="<%= image_path "switch/images/clr/businessltd.png" %>" alt="bootstrap business templates" class="active"></a>
        </div>
        <div class="themeName">Bootswatch Skins (11)</div>
        <div class="images style">
            <a href="themes/css/#" name="amelia" title="Amelia"><img src="<%= image_path "switch/images/clr/amelia.png" %>" alt="bootstrap business templates"></a>
            <a href="themes/css/#" name="spruce" title="Spruce"><img src="<%= image_path "switch/images/clr/spruce.png" %>" alt="bootstrap business templates" ></a>
            <a href="themes/css/#" name="superhero" title="Superhero"><img src="<%= image_path "switch/images/clr/superhero.png" %>" alt="bootstrap business templates"></a>
            <a href="themes/css/#" name="cyborg"><img src="<%= image_path "switch/images/clr/cyborg.png" %>" alt="bootstrap business templates"></a>
            <a href="themes/css/#" name="cerulean"><img src="<%= image_path "switch/images/clr/cerulean.png" %>" alt="bootstrap business templates"></a>
            <a href="themes/css/#" name="journal"><img src="<%= image_path "switch/images/clr/journal.png" %>" alt="bootstrap business templates"></a>
            <a href="themes/css/#" name="readable"><img src="<%= image_path "switch/images/clr/readable.png" %>" alt="bootstrap business templates"></a>
            <a href="themes/css/#" name="simplex"><img src="<%= image_path "switch/images/clr/simplex.png" %>" alt="bootstrap business templates"></a>
            <a href="themes/css/#" name="slate"><img src="<%= image_path "switch/images/clr/slate.png" %>" alt="bootstrap business templates"></a>
            <a href="themes/css/#" name="spacelab"><img src="<%= image_path "switch/images/clr/spacelab.png" %>" alt="bootstrap business templates"></a>
            <a href="themes/css/#" name="united"><img src="<%= image_path "switch/images/clr/united.png" %>" alt="bootstrap business templates"></a>
            <p style="margin:0;line-height:normal;margin-left:-10px;display:none;"><small>These are just examples and you can build your own color scheme in the backend.</small></p>
        </div>
        <div class="themeName">Background Patterns </div>
        <div class="images patterns">
            <a href="themes/css/#" name="pattern1"><img src="<%= image_path "switch/images/pattern/pattern1.png" %>" alt="bootstrap business templates" class="active"></a>
            <a href="themes/css/#" name="pattern2"><img src="<%= image_path "switch/images/pattern/pattern2.png" %>" alt="bootstrap business templates"></a>
            <a href="themes/css/#" name="pattern3"><img src="<%= image_path "switch/images/pattern/pattern3.png" %>" alt="bootstrap business templates"></a>
            <a href="themes/css/#" name="pattern4"><img src="<%= image_path "switch/images/pattern/pattern4.png" %>" alt="bootstrap business templates"></a>
            <a href="themes/css/#" name="pattern5"><img src="<%= image_path "switch/images/pattern/pattern5.png" %>" alt="bootstrap business templates"></a>
            <a href="themes/css/#" name="pattern6"><img src="<%= image_path "switch/images/pattern/pattern6.png" %>" alt="bootstrap business templates"></a>
            <a href="themes/css/#" name="pattern7"><img src="<%= image_path "switch/images/pattern/pattern7.png" %>" alt="bootstrap business templates"></a>
            <a href="themes/css/#" name="pattern8"><img src="<%= image_path "switch/images/pattern/pattern8.png" %>" alt="bootstrap business templates"></a>
            <a href="themes/css/#" name="pattern9"><img src="<%= image_path "switch/images/pattern/pattern9.png" %>" alt="bootstrap business templates"></a>
            <a href="themes/css/#" name="pattern10"><img src="<%= image_path "switch/images/pattern/pattern10.png" %>" alt="bootstrap business templates"></a>
            <a href="themes/css/#" name="pattern11"><img src="<%= image_path "switch/images/pattern/pattern11.png" %>" alt="bootstrap business templates"></a>
            <a href="themes/css/#" name="pattern12"><img src="<%= image_path "switch/images/pattern/pattern12.png" %>" alt="bootstrap business templates"></a>
            <a href="themes/css/#" name="pattern13"><img src="<%= image_path "switch/images/pattern/pattern13.png" %>" alt="bootstrap business templates"></a>
            <a href="themes/css/#" name="pattern14"><img src="<%= image_path "switch/images/pattern/pattern14.png" %>" alt="bootstrap business templates"></a>
            <a href="themes/css/#" name="pattern15"><img src="<%= image_path "switch/images/pattern/pattern15.png" %>" alt="bootstrap business templates"></a>
            <a href="themes/css/#" name="pattern16"><img src="<%= image_path "switch/images/pattern/pattern16.png" %>" alt="bootstrap business templates"></a>
            <a href="themes/css/#" name="pattern17"><img src="<%= image_path "switch/images/pattern/pattern17.png" %>" alt="bootstrap business templates"></a>
            <a href="themes/css/#" name="pattern18"><img src="<%= image_path "switch/images/pattern/pattern18.png" %>" alt="bootstrap business templates"></a>
            <a href="themes/css/#" name="pattern19"><img src="<%= image_path "switch/images/pattern/pattern19.png" %>" alt="bootstrap business templates"></a>
            <a href="themes/css/#" name="pattern20"><img src="<%= image_path "switch/images/pattern/pattern20.png" %>" alt="bootstrap business templates"></a>
        </div>
    </div>
</div>
<span id="themesBtn"></span>